/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Telegram Bot Admin Panel API
 * OpenAPI spec version: 0.1.0
 */

export interface BotStats {
  total_chats: number;
  total_users: number;
  total_warns: number;
  total_bans: number;
  total_notes: number;
  total_filters: number;
  total_gbans: number;
  total_logs: number;
  bot_uptime: string;
  active_chats_24h: number;
  federations: number;
}
